version: "3.9"

services:

  security-db:
    image: postgres:16
    container_name: security-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: seguridaddb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d seguridaddb"]
      interval: 5s
      timeout: 5s
      retries: 10

    ports:
      - "5432:5432"

    volumes:
      - security-db-data:/var/lib/postgresql/data
      - ./backend/security-service/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    networks:
      security-network:
        aliases:
          - security-db

  security-service:
    build:
      context: ./backend/security-service
      dockerfile: Dockerfile

    container_name: security-service
    restart: unless-stopped

    depends_on:
      security-db:
        condition: service_healthy

    ports:
      - "5001:5001"

    environment:
      DB_HOST: security-db
      DB_PORT: 5432
      DB_NAME: seguridaddb
      DB_USER: admin
      DB_PASSWORD: admin123

      JWT_SECRET_KEY: 1a6790ea7aee933b903e74fcaa2804dfbf61387d6c4d7cb61206fd32b211958b
      JWT_ALGORITHM: HS256
      JWT_ACCESS_TOKEN_EXPIRES: 900
      JWT_REFRESH_TOKEN_EXPIRES: 86400

      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: "bryanlopezleon8@gmail.com"
      SMTP_PASSWORD: "pmrr qtfc tntn bzea"
      SMTP_USE_TLS: "True"
      SMTP_USE_SSL: "False"
      SMTP_FROM_EMAIL: "Sistema de Tutorias <bryanlopezleon8@gmail.com>"
      SMTP_TIMEOUT: 10
      RESET_PASSWORD_URL_BASE: http://localhost:3000/reset-password

    networks:
      security-network:
        aliases:
          - security-service

volumes:
  security-db-data:

networks:
  security-network:
    external: true
    name: tutorias-mesh
