export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  RECOVER_PASSWORD: '/recuperar-password',
  CHAT: '/chat',
  TUTORIAS: '/tutorias',
  DATASET: '/dataset',
  ENTRENAMIENTO: '/entrenamiento',
  METRICAS: '/metricas',
  PENDIENTES: '/pendientes',
  PERFIL: '/perfil',
  DOCUMENTOS: '/documentos',
  CONFIGURACION: '/configuracion',
  LOGS: '/logs',
  ADMIN_USUARIOS: '/administracion/usuarios',
  ADMIN_ROLES: '/administracion/roles',
  ADMIN_PERMISOS: '/administracion/permisos',
  ACADEMICO_FACULTADES: '/academico/facultades',
  ACADEMICO_CARRERAS: '/academico/carreras',
  ACADEMICO_ESTUDIANTES: '/academico/estudiantes',
  ACADEMICO_DOCENTES: '/academico/docentes',
  ACADEMICO_MATERIAS: '/academico/materias',
  ACADEMICO_BITACORA: '/academico/bitacora',
} as const
